app/models/base.py
# Define a base model for other database tables to inherit
from app import db


class Base(db.Model):
    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    date_modified = db.Column(db.DateTime, default=db.func.current_timestamp(),
                              onupdate=db.func.current_timestamp())

app/modules/mod_auth/controller.py
# Import flask dependencies
import hashlib

from flask import Blueprint, render_template, flash, request, url_for, redirect, abort, session
from flask.ext.babel import gettext as _
from flask.ext.login import login_user, login_required, logout_user, current_user

from app import db
from app.models.user import User
from app.modules.mod_auth.forms import LoginForm

mod_auth = Blueprint("mod_auth", __name__, url_prefix="/auth")


@mod_auth.route("/login", methods=["GET", "POST"])
def login():
    """
    show log in page or log in a User
    :return: the log in page or redirect to the index page
    """

    # don't allow login when User is logged in already
    if current_user.is_authenticated:
        return redirect(url_for("mod_index.index"))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data,
                                    password=hashlib.sha256(form.password.data.encode("utf8")).hexdigest()).first()

        if user is not None:
            login_user(user, remember=form.remember.data)
            return redirect(request.args.get("next") or url_for("mod_index.index"))
        else:
            flash(_("Invalid Username or Password. Please try again!"), "error")

    return render_template("auth/login.html", form=form, title=_("Login"))


@mod_auth.route("/logout")
@login_required
def logout():
    """
    logout the current User
    :return: redirect to login
    """
    logout_user()
    return redirect(url_for("mod_auth.login"))


@mod_auth.route("/lang/<string:language>")
def set_language(language):
    """
    set a new language as active for the currently logged in User
    :param language: the new language
    :return: redirect to referrer
    """

    if language in ("de", "en"):
        # only store language in database when the User is logged in
        if current_user.is_authenticated:
            current_user.language = language
            db.session.commit()

        session["language"] = language
        return redirect(request.referrer or url_for("mod_index.index"))
    else:
        abort(404)

app/modules/mod_list/controller.py
import json

from flask import Blueprint, render_template, abort, request
from flask.ext.babel import gettext as _
from flask.ext.login import login_required

from app import db
from app.library.formatters import human_size, filename_description
from app.models.file import File
from app.models.package import Package
from app.modules.mod_process.process_repository import ProcessRepository
from app.modules.mod_process.status_map import StatusMap

mod_list = Blueprint("mod_list", __name__, url_prefix="/list")


@mod_list.route("/<string:which>")
@login_required
def show(which):
    """
    show the list page
    :param which: what list page to show: queue or collector
    :return: the list page
    """

    if which != "collector" and which != "queue":
        abort(404)

    queue = which == "queue"

    packages = Package.query.join(Package.files).filter(Package.queue == queue).options(
        db.contains_eager(Package.files)).order_by(Package.position.asc(), File.position.asc()).all()

    for package in packages:
        package.files_finished = 0
        package.size = 0

        for file in package.files:
            if file.status == StatusMap.finished.value:
                package.files_finished += 1

            package.size += file.size
            file.size = human_size(file.size)
            file.description = filename_description(file.filename)

        package.files_total = len(package.files)
        package.progress = round((package.files_finished / (package.files_total * 1.0) * 100))
        package.size = human_size(package.size)

    return render_template("list.html", packages=packages, StatusMap=StatusMap, js_name="list_js", css_name="list_css",
                           title=(_("Queue") if queue else _("Collector")))


@mod_list.route("/move_package", methods=["POST"])
@login_required
def move_package():
    """
    move a Package from queue to collector and vice-versa
    :return: ""
    """

    package_id = request.form["package_id"]

    package = Package.query.filter_by(id=package_id).first()

    if not package:
        abort(404)

    package.queue = not package.queue
    # respect the position by using the position of the last package of the target (package.queue)
    last_package = Package.query.filter_by(queue=package.queue).filter(Package.id != package.id).order_by(
        Package.position.desc()).limit(1).first()
    last_package_position = -1

    # only use last_package if available
    if last_package is not None:
        last_package_position = last_package.position

    package.position = last_package_position + 1
    db.session.commit()

    return ""


@mod_list.route("/restart_package", methods=["POST"])
@login_required
def restart_package():
    """
    restart a Package
    :return: ""
    """

    package_id = request.form["package_id"]

    package = Package.query.filter_by(id=package_id).first()
    if not package:
        abort(404)

    # cancel all currently running processes that belong to this package
    for file in package.files:
        if ProcessRepository.is_running(file.id):
            ProcessRepository.cancel_process(file.id)
        else:
            # clear progress, cancel_process() also does this
            file.clear()

        # set status of each file to "queued"
        file.status = StatusMap.queued.value

    db.session.commit()

    # check if it's necessary to start new processes
    ProcessRepository.check_and_start_processes()

    return ""


@mod_list.route("/restart_file", methods=["POST"])
@login_required
def restart_file():
    """
    restart a File
    :return: ""
    """

    file_id = request.form["file_id"]

    file = File.query.filter_by(id=file_id).first()
    if not file:
        abort(404)

    if ProcessRepository.is_running(file.id):
        ProcessRepository.cancel_process(file.id)
    else:
        # clear progress, cancel_process() also does this
        file.clear()

    # set status of file to "queued"
    file.status = StatusMap.queued.value

    db.session.commit()

    # check if it's necessary to start new processes
    ProcessRepository.check_and_start_processes()

    return ""


@mod_list.route("/delete_package", methods=["POST"])
@login_required
def delete_package():
    """
    delete a Package
    :return: ""
    """

    package_id = request.form["package_id"]

    package = Package.query.filter_by(id=package_id).first()
    if not package:
        abort(404)

    # cancel all currently running processes that belong to this package
    for file in package.files:
        if ProcessRepository.is_running(file.id):
            ProcessRepository.cancel_process(file.id)

        # mark this file to be deleted (even though SQLAlchemy handles this already)
        db.session.delete(file)

    db.session.delete(package)
    db.session.commit()

    # check if it's necessary to start new processes
    ProcessRepository.check_and_start_processes()

    return ""


@mod_list.route("/delete_file", methods=["POST"])
@login_required
def delete_file():
    """
    delete a File
    :return: ""
    """

    file_id = request.form["file_id"]
    file = File.query.filter_by(id=file_id).first()

    if not file:
        abort(404)

    # cancel the currently running processes that
    if ProcessRepository.is_running(file.id):
        ProcessRepository.cancel_process(file.id)

    db.session.delete(file)
    db.session.commit()

    # check if it's necessary to start new processes
    ProcessRepository.check_and_start_processes()

    return ""


@mod_list.route("/update_order", methods=["POST"])
@login_required
def update_order():
    """
    update the order of a Package or a File
    :return: ""
    """

    which = request.form["which"]  # "package" or "file"

    if which != "package" and which != "file":
        abort(404)

    # new_order is a list of entity IDs in their new order
    # i.e. [1, 2, 3] means ID 1 first, ID 2 second, ID 3 on the third place
    new_order = json.loads(request.form["new_order"])

    # query all elements at once
    if which == "package":
        elements = Package.query.filter(Package.id.in_(new_order)).all()
    else:
        elements = File.query.filter(File.id.in_(new_order)).all()

    for element in elements:
        # the new position is the position of the index in the list new_order
        element.position = new_order.index(element.id)

    db.session.commit()

    return ""

app/modules/mod_log/controller.py
import os
from math import ceil

from flask import render_template, Blueprint, abort
from flask.ext.login import login_required
from flask.ext.sqlalchemy import Pagination
from flask_babel import gettext as _

from app import app

mod_log = Blueprint("mod_log", __name__, url_prefix="/log")


@login_required
@mod_log.route("/", defaults={"page": 1}, methods=["GET"])
@mod_log.route("/page/<int:page>", methods=["GET"])
def log_page(page):
    """

    :param page: the page we are currently on
    :return: the log page
    """

    # read all log files into this variable
    content = ""
    for i in range(0, app.config["LOG_COUNT"]):
        file = app.config["LOG_FILE"]

        # add suffix if necessary
        if i != 0:
            file += "." + str(i)

        # only read file if it exists
        if not os.path.isfile(file):
            continue

        with open(file, "r") as content_file:
            content += content_file.read()

    entries = []

    lines = content.split("\n")

    for line in lines:
        # skip empty lines
        if len(line) == 0:
            continue

        line = line.strip()

        if not line[0].isnumeric():
            # this is definitely an exception line, because it does not start with a number
            # add it to the last item string
            entries[len(entries) - 1]["message"] += line + "\n\n"
            continue

        # separate date, time, the message is always the rest
        entry_date, entry_rest = line.split(" ", 1)
        entry_rest, entry_message = entry_rest.split("\t", 2)
        entry_time, entry_level = entry_rest.split(" ")

        entries.append({
            "date": entry_date,
            "time": entry_time,
            "level": entry_level,
            "message": entry_message.strip()
        })

    # show newest entries first
    entries.reverse()

    # pagination configuration
    per_page = 10
    total = len(entries)

    # check if we're out of bounds (page is greater than the highest page number)
    if page != 1 and page > ceil(total / per_page):
        abort(404)

    # slice entries appropriately
    offset = page * per_page - per_page
    cur_page_entries = entries[offset: offset + per_page]

    pagination = Pagination(None, page, per_page, total, cur_page_entries)

    return render_template("log.html", offset=offset, cur_page_entries=cur_page_entries, title=_("Log"), css_name="log_css",
                           pagination=pagination)

app/templates/structure/base.html
<!DOCTYPE html>
<html lang="{{ get_locale }}">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="shortcut icon" href="/static/favicon.ico"/>

    <title>{% if title is defined %}{{ title }}{% else %}pyEncode{% endif %}</title>

    {% assets (css_name if css_name else "base_css") %}
        <link rel="stylesheet" href="{{ ASSET_URL }}"/>
    {% endassets %}

    {% assets (js_name if js_name else "base_js") %}
        <script src="{{ ASSET_URL }}" async></script>
    {% endassets %}

    <script>
        var currentPath = "{{ '/filemanager' + path if path else '' }}";

        var lang = {
            success: "{{ _('Success') }}",
            process_cancel_success: "{{ _('The processes were cancelled successfully.') }}",
            error: "{{ _('Error') }}",
            warning: "{{ _('Warning') }}",
            not_all_fields_filled: "{{ _('Not all required fields were filled!') }}",
            package_added_successfully: "{{ _('The package was added successfully.') }}",
            duplicate_file_error: "{{ _('At least one file was added already!') }}",
            at_least_one_file_not_existing: "{{ _('At least one file does not exist!') }}",
            deleting_package_successful: "{{ _('The package has been deleted successfully.') }}",
            moving_package_successful: "{{ _('The package has been moved successfully.') }}",
            cant_open_folder: "{{ _('Can\'t open that folder!') }}",
            is_already_in_list: "{{ _('is already in your list!') }}",
            unknown_error_occured: "{{ _('An unknown error occured!') }}",
            file_has_been_added_successfully: "{{ _('The file has been added successfully.') }}",
            files_were_added_successfully: "{{ _('The files were added successfully.') }}",
            "remove_from_list": "{{ _('Remove from list') }}"
        }
    </script>
</head>
<body{% if filemanager is defined %} class="filemanager"{% endif %}>
{% if not filemanager is defined %}
    {% include "structure/menu.html" %}
{% endif %}
<div class="container">
    <div class="main">
        {% block content %}{% endblock %}
    </div>
</div>
{% if not current_user.is_anonymous and not filemanager is defined %}
    {% include "structure/statusbar.html" %}
{% endif %}
</body>
</html>

app/templates/structure/menu.html
<nav class="navbar navbar-static-top navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for("mod_index.index") }}">
                <i class="fa fa-fw fa-file-video-o"></i> pyEncode
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% if current_user.is_anonymous %}
                    <li{% if request.path == url_for("mod_auth.login") %} class="active"{% endif %}>
                        <a href="{{ url_for("mod_auth.login") }}">
                            <i class="fa fa-fw fa-unlock"></i> {{ _("Login") }}
                        </a>
                    </li>
                {% else %}
                    <li{% if request.path == url_for("mod_index.index") %} class="active"{% endif %}>
                        <a href="{{ url_for("mod_index.index") }}">
                            <i class="fa fa-fw fa-eye"></i> {{ _("Overview") }}
                        </a>
                    </li>
                    <li{% if request.path == url_for("mod_list.show", which="queue") %} class="active"{% endif %}>
                        <a href="{{ url_for("mod_list.show", which="queue") }}">
                            <i class="fa fa-fw fa-inbox"></i> {{ _("Queue") }}
                        </a>
                    </li>
                    <li{% if request.path == url_for("mod_list.show", which="collector") %} class="active"{% endif %}>
                        <a href="{{ url_for("mod_list.show", which="collector") }}">
                            <i class="fa fa-fw fa-shopping-cart"></i> {{ _("Collector") }}
                        </a>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-fw fa-language"></i> {{ _("Language") }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li{{ ' class="active"'|safe if get_locale == 'de' else '' }}>
                            <a href="{{ url_for("mod_auth.set_language", language="de") }}">
                                <i class="fa flag flag-de"></i> {{ _("German") }}
                            </a>
                        </li>
                        <li{{ ' class="active"'|safe if get_locale == "en" else "" }}>
                            <a href="{{ url_for("mod_auth.set_language", language="en") }}">
                                <i class="fa flag flag-us"></i> {{ _("English") }}
                            </a>
                        </li>
                    </ul>
                </li>
                {% if not current_user.is_anonymous %}
                    {#
                    <li{% if request.path == url_for("settings_page") %} class="active"{% endif %}>
                        <a href="{{ url_for("settings_page") }}">
                            <i class="fa fa-fw fa-cogs"></i> {{ _("Settings") }}
                        </a>
                    </li>
                    #}
                    <li{% if request.path == url_for("mod_log.log_page") %} class="active"{% endif %}>
                        <a href="{{ url_for("mod_log.log_page") }}">
                            <i class="fa fa-fw fa-file-text-o"></i> {{ _("Log") }}
                        </a>
                    </li>
                    <li>
                        <a href="{{ url_for("mod_auth.logout") }}">
                            <i class="fa fa-fw fa-lock"></i> {{ _("Logout") }}
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

app/templates/structure/statusbar.html
<div class="navbar navbar-fixed-bottom navbar-default" role="navigation">
    <div class="container">
        <div style="margin: 15px 0 15px 15px;">
            <div class="btn-toolbar">
                <div class="btn-group text-center">
                    <button class="btn btn-default btn-sm" disabled>
                        <span id="count-processes-active" title="{{ _("Active") }}">{{ count_processes_active() }}</span> / <span id="count-processes-queued" title="{{ _("Queued") }}">{{ count_processes_queued() }}</span> / <span id="count-processes-total" title="{{ _("Total") }}">{{ count_processes_total() }}</span>
                    </button>
                    <button class="btn btn-{% if not encoding_active() %}danger{% else %}success{% endif %} btn-sm control" id="toggle-status-btn">
                        <i class="fa fa-info"></i>&nbsp;
                        <span class="{% if not encoding_active() %}hidden{% endif %}" data-which="1">{{ _("Activated") }}</span>
                        <span class="{% if encoding_active() %}hidden{% endif %}" data-which="0">{{ _("Deactivated") }}</span>
                    </button>
                </div>
                <div class="btn-group text-center">
                    <button id="add-package-btn" class="btn btn-primary btn-sm">
                        <i class="fa fa-film"></i> <span>&nbsp;{{ _("Add Package") }}</span>
                    </button>
                </div>
                <div class="btn-group text-center">
                    <button class="btn btn-info btn-sm" id="cancel-processes-btn">
                        <i class="fa fa-ban"></i> <span>{{ _("Cancel current processes") }}</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="add-package-modal" tabindex="-1" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">{{ _("Add Package") }}</h4>
            </div>
            <form class="form-horizontal" role="form">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="title" class="col-sm-2 control-label">{{ _("Package Name") }}:</label>
                        <div class="col-sm-10">
                            <input class="form-control" id="title" placeholder="{{ _("Nice movie to process") }}" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="filenames" class="col-sm-2 control-label">{{ _("File Path(s)") }}:</label>
                        <div class="col-sm-10">
                            <ul id="filenames" style="min-height: 25px; word-wrap: break-word;"></ul>
                            <a href="#" class="btn btn-info btn-sm col-xs-12" id="browse-btn">{{ _("Browse") }}</a>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="target" class="col-sm-2 control-label">{{ _("Target") }}:</label>
                        <div class="col-sm-10">
                            <div class="radio">
                                <label>
                                    <input type="radio" name="target" id="target_queue" value="1" checked="checked" />
                                    {{ _("Queue") }}
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="target" id="target_collector" value="0" />
                                    {{ _("Collector") }}
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        <i class="fa fa-ban fa-fw"></i> {{ _("Cancel") }}
                    </button>
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-fw fa-plus"></i> {{ _("Add") }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>